import type { Metadata } from "next";
import Head from "next/head";
import "../globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Gunny Games",
  description: "Generated by create next app",
};

const Valorant = localFont({ src: "../../../public/fonts/Valorant.ttf" });
const Insomnia = localFont({ src: "../../../public/fonts/Insomnia.ttf" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://db.onlinewebfonts.com/c/b2437a24f47a94383eb02858f8a4df97?family=Insomnia"
        />
        <link
          rel="stylesheet"
          href="https://db.onlinewebfonts.com/c/e7322a6673613ab13604fadda3d20e56?family=VALORANT"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.css"
        />
      </Head>
      <body className={`${Valorant.className}`}>{children}</body>
    </html>
  );
}
